version: "1"

services:
  - name: my-django-backend
    type: web
    runtime: python
    buildCommand: cd my_project_aegbp && pip install -r requirements.txt
    startCommand: cd my_project_aegbp && gunicorn my_project_aegbp.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aegbp_database  # Nome do banco de dados no Render
          property: connectionString  # A URL completa de conexão ao banco de dados
