# nationalities.py

NATIONALITY_CHOICES = [
    ('GW', 'Guiné-Bissau'),
    ('PT', 'Portugal'),
    # Outras nacionalidades em ordem alfabética
    ('AF', 'Afeganistão'),
    ('ZA', 'África do Sul'),
    ('AL', 'Albânia'),
    ('DE', 'Alemanha'),
    ('AD', 'Andorra'),
    ('AO', 'Angola'),
    ('AI', 'Anguilla'),
    ('AQ', 'Antártica'),
    ('AG', 'Antígua e Barbuda'),
    ('SA', 'Arábia Saudita'),
    ('DZ', 'Argélia'),
    ('AR', 'Argentina'),
    ('AM', 'Armênia'),
    ('AW', 'Aruba'),
    ('AU', 'Austrália'),
    ('AT', 'Áustria'),
    ('AZ', 'Azerbaijão'),
    ('BS', 'Bahamas'),
    ('BH', 'Bahrein'),
    ('BD', 'Bangladesh'),
    ('BB', 'Barbados'),
    ('BY', 'Bielorrússia'),
    ('BE', 'Bélgica'),
    ('BZ', 'Belize'),
    ('BJ', 'Benim'),
    ('BM', 'Bermudas'),
    ('BO', 'Bolívia'),
    ('BA', 'Bósnia e Herzegovina'),
    ('BW', 'Botswana'),
    ('BR', 'Brasil'),
    ('BN', 'Brunei'),
    ('BG', 'Bulgária'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('BT', 'Butão'),
    ('CV', 'Cabo Verde'),
    ('KH', 'Camboja'),
    ('CM', 'Camarões'),
    ('CA', 'Canadá'),
    ('QA', 'Catar'),
    ('KZ', 'Cazaquistão'),
    ('TD', 'Chade'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CY', 'Chipre'),
    ('SG', 'Cingapura'),
    ('CO', 'Colômbia'),
    ('KM', 'Comores'),
    ('CG', 'Congo - Brazzaville'),
    ('CD', 'Congo - Kinshasa'),
    ('KR', 'Coreia do Sul'),
    ('KP', 'Coreia do Norte'),
    ('CR', 'Costa Rica'),
    ('CI', 'Costa do Marfim'),
    ('HR', 'Croácia'),
    ('CU', 'Cuba'),
    ('CW', 'Curaçao'),
    ('DK', 'Dinamarca'),
    ('DJ', 'Djibuti'),
    ('DM', 'Dominica'),
    ('EG', 'Egito'),
    ('SV', 'El Salvador'),
    ('AE', 'Emirados Árabes Unidos'),
    ('EC', 'Equador'),
    ('ER', 'Eritreia'),
    ('SK', 'Eslováquia'),
    ('SI', 'Eslovênia'),
    ('ES', 'Espanha'),
    ('US', 'Estados Unidos'),
    ('EE', 'Estônia'),
    ('ET', 'Etiópia'),
    ('FJ', 'Fiji'),
    ('PH', 'Filipinas'),
    ('FI', 'Finlândia'),
    ('FR', 'França'),
    ('GA', 'Gabão'),
    ('GM', 'Gâmbia'),
    ('GH', 'Gana'),
    ('GE', 'Geórgia'),
    ('GS', 'Geórgia do Sul e Ilhas Sandwich do Sul'),
    ('GI', 'Gibraltar'),
    ('GR', 'Grécia'),
    ('GD', 'Granada'),
    ('GL', 'Groenlândia'),
    ('GP', 'Guadalupe'),
    ('GU', 'Guam'),
    ('GT', 'Guatemala'),
    ('GG', 'Guernsey'),
    ('GY', 'Guiana'),
    ('GF', 'Guiana Francesa'),
    ('HT', 'Haiti'),
    ('HN', 'Honduras'),
    ('HK', 'Hong Kong, RAE da China'),
    ('HU', 'Hungria'),
    ('YE', 'Iêmen'),
    ('BV', 'Ilha Bouvet'),
    ('IM', 'Ilha de Man'),
    ('CX', 'Ilha Natal'),
    ('NF', 'Ilha Norfolk'),
    ('AX', 'Ilhas Aland'),
    ('KY', 'Ilhas Cayman'),
    ('CC', 'Ilhas Cocos (Keeling)'),
    ('CK', 'Ilhas Cook'),
    ('FO', 'Ilhas Faroe'),
    ('FK', 'Ilhas Malvinas'),
    ('MP', 'Ilhas Marianas do Norte'),
    ('MH', 'Ilhas Marshall'),
    ('UM', 'Ilhas Menores Distantes dos EUA'),
    ('PN', 'Ilhas Pitcairn'),
    ('SB', 'Ilhas Salomão'),
    ('TC', 'Ilhas Turks e Caicos'),
    ('VG', 'Ilhas Virgens Britânicas'),
    ('VI', 'Ilhas Virgens dos EUA'),
    ('IN', 'Índia'),
    ('ID', 'Indonésia'),
    ('IR', 'Irã'),
    ('IQ', 'Iraque'),
    ('IE', 'Irlanda'),
    ('IS', 'Islândia'),
    ('IL', 'Israel'),
    ('IT', 'Itália'),
    ('JM', 'Jamaica'),
    ('JP', 'Japão'),
    ('JE', 'Jersey'),
    ('JO', 'Jordânia'),
    ('KW', 'Kuwait'),
    ('LA', 'Laos'),
    ('LS', 'Lesoto'),
    ('LV', 'Letônia'),
    ('LB', 'Líbano'),
    ('LR', 'Libéria'),
    ('LY', 'Líbia'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lituânia'),
    ('LU', 'Luxemburgo'),
    ('MO', 'Macau, RAE da China'),
    ('MK', 'Macedônia do Norte'),
    ('MG', 'Madagascar'),
    ('MY', 'Malásia'),
    ('MW', 'Malawi'),
    ('MV', 'Maldivas'),
    ('ML', 'Mali'),
    ('MT', 'Malta'),
    ('MA', 'Marrocos'),
    ('MQ', 'Martinica'),
    ('MR', 'Mauritânia'),
    ('MU', 'Maurício'),
    ('YT', 'Mayotte'),
    ('MX', 'México'),
    ('FM', 'Micronésia'),
    ('MZ', 'Moçambique'),
    ('MD', 'Moldova'),
    ('MC', 'Mônaco'),
    ('MN', 'Mongólia'),
    ('ME', 'Montenegro'),
    ('MS', 'Montserrat'),
    ('MM', 'Mianmar (Birmânia)'),
    ('NA', 'Namíbia'),
    ('NR', 'Nauru'),
    ('NP', 'Nepal'),
    ('NI', 'Nicarágua'),
    ('NE', 'Níger'),
    ('NG', 'Nigéria'),
    ('NU', 'Niue'),
    ('NO', 'Noruega'),
    ('NC', 'Nova Caledônia'),
    ('NZ', 'Nova Zelândia'),
    ('OM', 'Omã'),
    ('NL', 'Países Baixos'),
    ('PW', 'Palau'),
    ('PS', 'Palestina'),
    ('PA', 'Panamá'),
    ('PG', 'Papua-Nova Guiné'),
    ('PK', 'Paquistão'),
    ('PY', 'Paraguai'),
    ('PE', 'Peru'),
    ('PF', 'Polinésia Francesa'),
    ('PL', 'Polônia'),
    ('PR', 'Porto Rico'),
    ('QA', 'Qatar'),
    ('KE', 'Quênia'),
    ('KG', 'Quirguistão'),
    ('GB', 'Reino Unido'),
    ('RE', 'Reunião'),
    ('RO', 'Romênia'),
    ('RW', 'Ruanda'),
    ('RU', 'Rússia'),
    ('EH', 'Saara Ocidental'),
    ('PM', 'Saint Pierre e Miquelon'),
    ('WS', 'Samoa'),
    ('AS', 'Samoa Americana'),
    ('SM', 'San Marino'),
    ('SH', 'Santa Helena'),
    ('LC', 'Santa Lúcia'),
    ('BL', 'Saint Barthélemy'),
    ('KN', 'Saint Kitts e Nevis'),
    ('MF', 'Saint Martin'),
    ('ST', 'São Tomé e Príncipe'),
    ('VC', 'São Vicente e Granadinas'),
    ('SN', 'Senegal'),
    ('SL', 'Serra Leoa'),
    ('RS', 'Sérvia'),
    ('SC', 'Seychelles'),
    ('SG', 'Singapura'),
    ('SX', 'Sint Maarten'),
    ('SY', 'Síria'),
    ('SO', 'Somália'),
    ('LK', 'Sri Lanka'),
    ('SZ', 'Suazilândia'),
    ('SD', 'Sudão'),
    ('SS', 'Sudão do Sul'),
    ('SE', 'Suécia'),
    ('CH', 'Suíça'),
    ('SR', 'Suriname'),
    ('SJ', 'Svalbard e Jan Mayen'),
    ('TH', 'Tailândia'),
    ('TW', 'Taiwan'),
    ('TJ', 'Tajiquistão'),
    ('TZ', 'Tanzânia'),
    ('CZ', 'Tchéquia'),
    ('TF', 'Territórios Franceses do Sul'),
    ('IO', 'Território Britânico do Oceano Índico'),
    ('TL', 'Timor-Leste'),
    ('TG', 'Togo'),
    ('TK', 'Tokelau'),
    ('TO', 'Tonga'),
    ('TT', 'Trinidad e Tobago'),
    ('TN', 'Tunísia'),
    ('TM', 'Turcomenistão'),
    ('TR', 'Turquia'),
    ('TV', 'Tuvalu'),
    ('UA', 'Ucrânia'),
    ('UG', 'Uganda'),
    ('UY', 'Uruguai'),
    ('UZ', 'Uzbequistão'),
    ('VU', 'Vanuatu'),
    ('VA', 'Vaticano'),
    ('VE', 'Venezuela'),
    ('VN', 'Vietnã'),
    ('WF', 'Wallis e Futuna'),
    ('ZM', 'Zâmbia'),
    ('ZW', 'Zimbábue')
]
