# Generated by Django 5.1 on 2024-08-14 19:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('title_pt', models.CharField(max_length=200, null=True, verbose_name='Título')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('description_pt', models.TextField(null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(null=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobre',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('address_pt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('phone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1')),
                ('phone1_pt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1')),
                ('phone1_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('phone2_pt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('phone2_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('email1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 1')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 2')),
                ('days_of_week', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dias da Semana')),
                ('days_of_week_pt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dias da Semana')),
                ('days_of_week_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dias da Semana')),
                ('hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horários')),
                ('hours_pt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horários')),
                ('hours_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horários')),
            ],
            options={
                'verbose_name': 'Informação de Contato',
                'verbose_name_plural': 'Informações de Contato',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('name_pt', models.CharField(max_length=255, null=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('subject_pt', models.CharField(max_length=255, null=True, verbose_name='Assunto')),
                ('subject_en', models.CharField(max_length=255, null=True, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('message_pt', models.TextField(null=True, verbose_name='Mensagem')),
                ('message_en', models.TextField(null=True, verbose_name='Mensagem')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('status', models.CharField(default='novo', max_length=50, verbose_name='Status')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lido')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('title_pt', models.CharField(max_length=200, null=True, verbose_name='Título')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Título')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Arquivo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('description_pt', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('name_pt', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('description_pt', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('proof', models.FileField(blank=True, null=True, upload_to='donation_proofs/', verbose_name='Comprovante')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('name_pt', models.CharField(max_length=200, null=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Nome')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('description_pt', models.TextField(null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(null=True, verbose_name='Descrição')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Início')),
                ('end_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Término')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN')),
                ('mb_way_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número MB Way')),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('document_number', models.CharField(max_length=100, unique=True, verbose_name='Número do Documento')),
                ('document_type', models.CharField(choices=[('CC', 'Cartão de Cidadão'), ('PP', 'Passaporte'), ('AR', 'Autorização de Residência')], max_length=2, verbose_name='Tipo de Documento')),
                ('document_validity', models.DateField(verbose_name='Validade do Documento')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nacionalidade')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não dizer')], max_length=1, verbose_name='Gênero')),
                ('other_gender', models.CharField(blank=True, max_length=100, null=True, verbose_name='Outro Gênero')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_student', models.BooleanField(default=False, verbose_name='É Estudante')),
                ('school', models.CharField(blank=True, max_length=255, null=True, verbose_name='Escola')),
                ('education_type', models.CharField(blank=True, choices=[('S', 'Superior'), ('P', 'Profissional'), ('T', 'Secundário')], max_length=1, null=True, verbose_name='Tipo de Educação')),
                ('course', models.CharField(blank=True, max_length=255, null=True, verbose_name='Curso')),
                ('academic_year', models.IntegerField(blank=True, null=True, verbose_name='Ano Acadêmico')),
                ('is_scholar', models.BooleanField(default=False, verbose_name='É Bolseiro')),
                ('is_working_student', models.BooleanField(default=False, verbose_name='É Estudante Trabalhador')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ocupação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10, verbose_name='Status')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lido')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Política de Privacidade',
                'verbose_name_plural': 'Políticas de Privacidade',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('title_pt', models.CharField(max_length=200, null=True, verbose_name='Título')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Título')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('description_pt', models.TextField(null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('other', 'Outro')], max_length=20, verbose_name='Plataforma')),
                ('profile_name', models.CharField(max_length=100, verbose_name='Nome do Perfil')),
                ('profile_name_pt', models.CharField(max_length=100, null=True, verbose_name='Nome do Perfil')),
                ('profile_name_en', models.CharField(max_length=100, null=True, verbose_name='Nome do Perfil')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Mídia Social',
                'verbose_name_plural': 'Mídias Sociais',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('name_pt', models.CharField(max_length=200, null=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Nome')),
                ('logo', models.ImageField(upload_to='sponsors/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('description_pt', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('name_pt', models.CharField(max_length=200, null=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Nome')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('content_pt', models.TextField(null=True, verbose_name='Conteúdo')),
                ('content_en', models.TextField(null=True, verbose_name='Conteúdo')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('title_pt', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('description_pt', models.TextField(null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(null=True, verbose_name='Descrição')),
                ('location', models.CharField(default='Desconhecido', max_length=100, verbose_name='Localização')),
                ('location_pt', models.CharField(default='Desconhecido', max_length=100, null=True, verbose_name='Localização')),
                ('location_en', models.CharField(default='Desconhecido', max_length=100, null=True, verbose_name='Localização')),
                ('date', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Oportunidade de Voluntariado',
                'verbose_name_plural': 'Oportunidades de Voluntariado',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('title_pt', models.CharField(max_length=200, null=True, verbose_name='Título')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('content_pt', models.TextField(null=True, verbose_name='Conteúdo')),
                ('content_en', models.TextField(null=True, verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Imagem')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Postagem do Blog',
                'verbose_name_plural': 'Postagens do Blog',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('content_pt', models.TextField(null=True, verbose_name='Conteúdo')),
                ('content_en', models.TextField(null=True, verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='my_aegbp.blogpost', verbose_name='Postagem')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Pergunta')),
                ('question_pt', models.CharField(max_length=200, null=True, verbose_name='Pergunta')),
                ('question_en', models.CharField(max_length=200, null=True, verbose_name='Pergunta')),
                ('answer', models.TextField(verbose_name='Resposta')),
                ('answer_pt', models.TextField(null=True, verbose_name='Resposta')),
                ('answer_en', models.TextField(null=True, verbose_name='Resposta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_aegbp.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200, verbose_name='Remetente')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='my_aegbp.contactmessage', verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda')),
                ('caption_pt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda')),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='my_aegbp.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='ProjectImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(verbose_name='Relatório')),
                ('date', models.DateField(verbose_name='Data')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='my_aegbp.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Impacto do Projeto',
                'verbose_name_plural': 'Impactos do Projeto',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('name_pt', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='my_aegbp.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Foto de Perfil')),
                ('job_title', models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, default='', max_length=10, verbose_name='CEP')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
            ],
            options={
                'verbose_name': 'Perfil de utilizador',
                'verbose_name_plural': 'Perfis de utilizadors',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Título Padrão', max_length=200, verbose_name='Título')),
                ('title_pt', models.CharField(default='Título Padrão', max_length=200, null=True, verbose_name='Título')),
                ('title_en', models.CharField(default='Título Padrão', max_length=200, null=True, verbose_name='Título')),
                ('description', models.TextField(default='Descrição Padrão', verbose_name='Descrição')),
                ('description_pt', models.TextField(default='Descrição Padrão', null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(default='Descrição Padrão', null=True, verbose_name='Descrição')),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Arquivo')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='my_aegbp.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_aegbp.volunteeropportunity', verbose_name='Oportunidade')),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
            },
        ),
    ]
